# Generated by Django 5.2.6 on 2026-03-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attendance',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Attended', 'Attended'), ('Missed', 'Missed')], default='Pending', max_length=20),
        ),
    ]
